apiVersion:  v1  #acts a manuall to your system
kind: Pod
metadata:  #like a tag
        name: mytodoapp
        namespace: mytodonamespace
        labels: 
           app: mytodoapp
spec:
 containers:
    - name: mypod-cont1
      image: poonam1006/todo        
      ports:  
        - name: http
          containerPort: 80
          protocol: TCP
---

apiVersion: v1 
kind: Service
metadata:
        name: my-service1 #cluster
        namespace: mytodonamespace 
spec:
    selector:
          app: mytodoapp
    type: LoadBalancer
    ports:
    - protocol: TCP
      port: 80
      #targetPort: 80
      name: todo
