apiVersion:  v1  #acts a manuall to your system
kind: Pod
metadata:  #like a tag
        name: mytodoapp
        namespace: mytodoappnamespace
spec:
 containers:
    - name: mypod-cont1
      image: poonam1006/todo
      resources: 
          requests:
            cpu: "50m"
            memory: "90Mi"        
      ports:  
        - name: http
          containerPort: 80
          protocol: TCP
---

apiVersion: v1 
kind: Service
metadata:
        name: my-service #cluster
        namespace: mytodonamespace 
spec:
    selector:
          app: mytodoapp
    type: LoadBalancer
    ports:
    - protocol: TCP
      port: 80
      #targetPort: 80
      name: todo
